apiVersion: v1
kind: Pod
metadata:
  name: ndn-func-poc
spec:
  containers:
    - name: ndn-fcw-sidecar
      image: ndn-fcw-sidecar:v15
      imagePullPolicy: IfNotPresent
    - name: user-function
      image: function-image:v15
      imagePullPolicy: IfNotPresent
