apiVersion: v1
kind: Pod
metadata:
  name: ndn-func-poc
spec:
  containers:
    - name: ndn-fcw-sidecar
      image: harutokobayashi/ndn-fcw-sidecar
      imagePullPolicy: IfNotPresent
      env:
        - name: NLSR_CONFIG_FILE_PATH
          value: "/app/nlsr.conf"
        - name: NDN_FUNCTION_PREFIX
          value: "/func_nodeX"
      volumeMounts:
        - name: nlsr-config-volume
          mountPath: /app/nlsr.conf
          subPath: nlsr.conf

    # - name: user-function
    #   image: your-registry/ndn-function:latest
    #   imagePullPolicy: IfNotPresent

    - name: user-function
      image: function-image:v13
      imagePullPolicy: IfNotPresent

  volumes:
    - name: nlsr-config-volume
      configMap:
        name: nlsr-config
