apiVersion: v1
kind: Pod
metadata:
  name: ndn-func-demo
spec:
  containers:
    - name: ndn-fcw-sidecar
      image: harutokobayashi/ndn-fcw-sidecar:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: NLSR_CONFIG_FILE_PATH
          value: "/app/nlsr.conf"
        - name: NDN_FUNCTION_PREFIX
          value: "/func_demo"
      volumeMounts:
        - name: nlsr-config-volume
          mountPath: /app/nlsr.conf
          subPath: nlsr.conf

    - name: user-function
      image: harutokobayashi/ndn-fcw-function-demo:latest # 自分の関数をビルドして push したもの
      imagePullPolicy: IfNotPresent

  volumes:
    - name: nlsr-config-volume
      configMap:
        name: nlsr-config
